enum QuestionaryActionTypes {
    PROFILES_LOADED = "PROFILES_LOADED",
    PROFILE_SELECTED = "PROFILE_SELECTED",
    VISITOR_LOADED = "VISITOR_LOADED",
    QUESTIONARY_LOADED = "QUESTIONARY_LOADED",
    QUESTION_ANSWERED = "QUESTION_ANSWERED",
    QUESTIONARY_COMPLETED = "QUESTIONARY_COMPLETED"
}

export default QuestionaryActionTypes;